# specific path build
trigger:
  branches:
    include:
    - master
    - main
  paths:
    exclude:
    - devops/azure-pipelines/build.base.yml
    - devops/docker/Dockerfile.base

pool:
  vmImage: 'ubuntu-latest'
variables:
  buildContext: .
  dockerFile: 'devops/docker/Dockerfile.prod'
  imageName: 'marcskovmadsen/awesome-panel'
  dockerFileTest: 'devops/docker/Dockerfile.test'
  imageNameTest: 'marcskovmadsen/awesome-panel_test'
  dockerRegistry: 'dockerhub-awesome-panel'

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: $(dockerRegistry)
- task: Docker@0
  displayName: 'Build the Prod image'
  inputs:
    dockerFile: $(dockerFile)
    imageName: '$(imageName):$(Build.BuildId)'
    defaultContext: False
    context: $(buildContext)
- task: Docker@0
  displayName: 'Build the latest Prod image'
  inputs:
    dockerFile: $(dockerFile)
    imageName: '$(imageName):latest'
    defaultContext: False
    context: $(buildContext)
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerRegistry)
    repository: $(imageName)
    command: push
    tags: |
      $(Build.BuildId)
      latest
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Dockerfile'
  inputs:
    PathtoPublish: $(dockerFile)
    ArtifactName: $(imageName)